Repository gearnode/judge, pull requests merged in 2018-05, with the labels that each got.

#2 Object Resource Name (a.k.a ORN)
  orn/README.md
  orn/orn.go
  orn/orn_test.go
Labels: Kind:Enhancement

#4 Add package documentation
  orn/README.md
Labels: Kind:Documentation

#3 Add Authorize function
  policy.go
  policy_test.go
  resource.go
  resource_test.go
Labels: Kind:Enhancement, State:Draft

#7 Basic benchmarks for Authorize and Match
  policy_test.go
  resource_test.go
Labels: Kind:Enhancement
